version: "2.5"
services:

  webserver:
    image: nginx:alpine
    container_name: docker-setup-test-webserver
    working_dir: /application
    volumes:
      - .:/application:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    image: ghcr.io/tiendschuur/create-docker-image:latest
    container_name: docker-setup-test-php-fpm
    working_dir: /application
    volumes:
      - .:/application:cached
