version: "2.5"
services:

  webserver:
    image: nginx:alpine
    container_name: docker-setup-test-webserver
    working_dir: /application
    volumes:
      - .:/application:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "10003:80"

  node:
    build: docker/node
    container_name: docker-setup-test-node
    entrypoint: ["docker/node/entrypoint.sh"]
    working_dir: /application
    volumes:
      - .:/application:cached

  php-fpm:
    build: docker/php-fpm
    container_name: docker-setup-test-php-fpm
    working_dir: /application
    entrypoint: ["docker/php-fpm/entrypoint.sh"]
    volumes:
      - .:/application:cached
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
