name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: create version number
        run: echo "version=$(echo 'v1.0.${{github.run_number}}')" >> $GITHUB_ENV
      - name: Build (and push)
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: zbrag/create-docker-image:latest,zbrag/create-docker-image:${{ env.version }}
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: Release ${{ env.version }}
