name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  php-fpm:
    runs-on: ubuntu-latest
    steps:
      - name: create version number
        run: echo "version=$(echo 'v1.0.${{github.run_number}}')" >> $GITHUB_ENV
      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build_php
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          target: php-fpm
          push: true
          tags: ghcr.io/tiendschuur/create-docker-php-fpm:latest,ghcr.io/tiendschuur/create-docker-php-fpm:${{ env.version }}

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: Release ${{ env.version }}
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  nginx:
    runs-on: ubuntu-latest
    steps:
      - name: create version number
        run: echo "version=$(echo 'v1.0.${{github.run_number}}')" >> $GITHUB_ENV
      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build_nginx
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          target: nginx
          tags: ghcr.io/tiendschuur/create-docker-nginx:latest,ghcr.io/tiendschuur/create-docker-nginx:${{ env.version }}
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
