name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print new run number
        run: echo "Run number is $GITHUB_RUN_NUMBER, Run id $GITHUB_RUN_ID"