- uses: travisj/build-number-action@v1
  id: docker-setup-test-build-number

- name: Echo Build Number
  run: echo $BUILD_NUMBER
  env:
    BUILD_NUMBER: ${{ steps.docker-setup-test-build-number.outputs.build-number }}