name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate build number
        uses: einaregilsson/build-number@v2
        with:
          token: ${{secrets.github_token}}
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"